Environment: ENVIRONMENT
Azure:
    BlobStorageConnectionString: BLOBSTORAGECONNECTIONSTRING
DB:
  ConnectionString: CONNECTIONSTRING
EDS:
  Url: EDSURL
  UserName: EDSUSERNAME
  Password: EDSPASSWORD
WebAuth:
  Url: WEBAUTHURL
General:
  ConfigSettingExample: GENERALCONFIGSETTING
Logging:
    Retention: 7
    Sink: Blob