# GITHUB VERSION
# DO NOT USE THIS FILE AS THE APP CONFIG
# DO NOT REPLACE THE FIELDS WITH USEABLE VALUE
# ONLY USE AS THE CONFIGURATION STRUCTURE 
# THIS FILE WILL BE COPIED AND THE FIELDS REPLACED DURING BUILD ON TEAMCITY
Environment: ENVIRONMENT
Azure:
    BlobStorageConnectionString: BLOBSTORAGECONNECTIONSTRING
DB:
  ConnectionString: CONNECTIONSTRING
EDS:
  Url: EDSURL
  UserName: EDSUSERNAME
  Password: EDSPASSWORD
WebAuth:
  Url: WEBAUTHURL
General:
  ConfigSettingExample: GENERALCONFIGSETTING
Logging:
    Retention: RETENTION
    Sink: SINK
# DO NOT USE THIS FILE AS THE APP CONFIG
# DO NOT REPLACE THE FIELDS WITH USEABLE VALUE
# ONLY USE AS THE CONFIGURATION STRUCTURE 
# THIS FILE WILL BE COPIED AND THE FIELDS REPLACED DURING BUILD ON TEAMCITY
# GITHUB VERSION